### ISSUE TITLE
Supprimer les Security Credential du script

### ISSUE THREAD

**Issue by ghost** [hanfi/EC2-MongoDb-Snapshot#1]
Afin de sécuriser ce script, je propose d'utiliser des Tempory Credentials basés sur les IAM roles afin de ne pas à avoir à stocker des informations sensibles

cf http://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html#use-roles

-- Eric

**Comment by hanfi** [comment]
Je dois juste faire un test, mais en principe le AWS CLI récupère automatiquement les credentials depuis l'IAM ROLE si ils sont présents.

au pire il faut juste ajouter une clause IF qui check la présence d'IAM Role dans les metas.

**Comment by hanfi** [comment]
c'est bon ça n'a pas été facile de l'implementer, maintenant il supporte 4 type d'auth, IAM ROLE, Fichier de Conf, variables d'env, et param de la commande. 

Fonctionne parfaitement, n'hésitez pas à tester pour sortir plus de bugs.
